#!/bin/bash
# ============================================================
#  premium-setup.sh — Build the 3-layer brain for a user
#
#  Run this AFTER add-claw.sh, for premium/pro users.
#  It creates the full memory architecture inside their volume.
#
#  Usage: ./premium-setup.sh <username>
#  Example: ./premium-setup.sh sarah
# ============================================================
set -e

NAME=$1
NAME_LOWER=$(echo "$NAME" | tr '[:upper:]' '[:lower:]')
CONTAINER="claw-${NAME_LOWER}"

[ -z "$NAME" ] && echo "Usage: ./premium-setup.sh <username>" && exit 1

# Check container exists
docker inspect "$CONTAINER" > /dev/null 2>&1 || {
  echo "❌  Container $CONTAINER not found. Run add-claw.sh first."
  exit 1
}

echo ""
echo "🧠  Building premium brain for: $NAME"
echo "────────────────────────────────────────────────────"

# ══════════════════════════════════════════════════════════
#  STEP 1 — Create the 3-layer memory folder structure
#  We run a one-shot container against their volume to
#  create folders without needing to enter the container.
# ══════════════════════════════════════════════════════════
echo "📁  Creating memory folder structure..."

docker run --rm \
  -v "${NAME_LOWER}-data:/home/claw/.openclaw" \
  alpine sh -c "
    mkdir -p /home/claw/.openclaw/memory/daily
    mkdir -p /home/claw/.openclaw/memory/graph
    mkdir -p /home/claw/.openclaw/memory/tacit
    mkdir -p /home/claw/.openclaw/brain/qmd-index
    mkdir -p /home/claw/.openclaw/agents
    mkdir -p /home/claw/.openclaw/secrets
    echo 'folders created'
  "

echo "✅  Memory folders created:
    memory/daily/   ← chat session logs
    memory/graph/   ← knowledge graph (entity relationships)
    memory/tacit/   ← preferences, lessons, rules
    brain/qmd-index/ ← fast search index
    agents/         ← parallel task threads
    secrets/        ← isolated API keys"

# ══════════════════════════════════════════════════════════
#  STEP 2 — Write config.yaml (reflection + auto-improve on)
# ══════════════════════════════════════════════════════════
echo ""
echo "⚙️   Writing config.yaml (reflection enabled)..."

docker run --rm \
  -v "${NAME_LOWER}-data:/home/claw/.openclaw" \
  alpine sh -c "cat > /home/claw/.openclaw/config.yaml << 'YAML'
# OpenClaw Premium Config — auto-generated by premium-setup.sh
# Based on Peter Steinberger + Nat Eliason's tested setup

memory:
  daily: true          # log every chat session
  graph: true          # build knowledge graph across conversations
  tacit: true          # extract preferences and lessons learned
  consolidation: true  # nightly merge of all 3 layers

brain:
  reflection: true     # agent reviews its own outputs and improves
  auto_improve: true   # system prompt updated based on reflection
  qmd_index: true      # fast markdown search across all memory

agents:
  multi_thread: true   # allow parallel agent tasks
  max_threads: 5       # max concurrent agents (adjust for RAM)

heartbeat:
  enabled: true
  interval_minutes: 60         # check long-running tasks every hour
  proactive_nudges: true        # remind user of pending items

security:
  secrets_isolated: true       # secrets/ folder is least-privilege
  least_privilege: true
YAML
echo 'config written'"

echo "✅  config.yaml written (reflection + auto-improve ON)"

# ══════════════════════════════════════════════════════════
#  STEP 3 — Write cron-nightly.sh (2AM consolidation)
#  This merges daily notes → updates graph → refreshes tacit
#  knowledge. Runs inside the container every night.
# ══════════════════════════════════════════════════════════
echo ""
echo "🌙  Writing nightly consolidation script..."

docker run --rm \
  -v "${NAME_LOWER}-data:/home/claw/.openclaw" \
  alpine sh -c "cat > /home/claw/.openclaw/brain/cron-nightly.sh << 'BASH'
#!/bin/sh
# cron-nightly.sh — Runs at 2AM every night
# Consolidates the 3 memory layers so the agent wakes up smarter

LOG=/home/claw/.openclaw/brain/nightly.log
DATE=\$(date +\"%Y-%m-%d %H:%M\")

echo \"[\$DATE] Starting nightly consolidation...\" >> \$LOG

# 1. Archive today's daily notes
TODAY=\$(date +\"%Y-%m-%d\")
DAILY_DIR=/home/claw/.openclaw/memory/daily
if [ -d \"\$DAILY_DIR\" ]; then
  NOTE_COUNT=\$(ls \"\$DAILY_DIR\" 2>/dev/null | wc -l)
  echo \"[\$DATE] Found \$NOTE_COUNT daily notes\" >> \$LOG
fi

# 2. Ask OpenClaw to consolidate memories
# OpenClaw reads this trigger file and runs its own consolidation
echo \"\$DATE\" > /home/claw/.openclaw/brain/.consolidate-trigger

# 3. Rebuild QMD search index
INDEX_DIR=/home/claw/.openclaw/brain/qmd-index
MEMORY_DIR=/home/claw/.openclaw/memory
if command -v find > /dev/null; then
  find \"\$MEMORY_DIR\" -name \"*.md\" -newer \"\$INDEX_DIR/.last-indexed\" \
    2>/dev/null | while read f; do
    echo \"\$f\" >> \"\$INDEX_DIR/pending-index.txt\"
  done
  touch \"\$INDEX_DIR/.last-indexed\"
fi

echo \"[\$DATE] Nightly consolidation complete\" >> \$LOG
BASH
chmod +x /home/claw/.openclaw/brain/cron-nightly.sh
echo 'cron written'"

echo "✅  cron-nightly.sh written (runs at 2AM)"

# ══════════════════════════════════════════════════════════
#  STEP 4 — Write heartbeat.py
#  Checks long-running tasks every hour.
#  Sends proactive Telegram nudges if tasks are stuck.
# ══════════════════════════════════════════════════════════
echo ""
echo "💓  Writing heartbeat monitor..."

docker run --rm \
  -v "${NAME_LOWER}-data:/home/claw/.openclaw" \
  alpine sh -c "cat > /home/claw/.openclaw/brain/heartbeat.py << 'PYTHON'
#!/usr/bin/env python3
\"\"\"
heartbeat.py — Monitors long-running tasks and sends proactive nudges.
OpenClaw calls this periodically to check agent health.
\"\"\"
import os, json, time
from datetime import datetime, timedelta
from pathlib import Path

OPENCLAW_DIR = Path.home() / '.openclaw'
TASKS_FILE   = OPENCLAW_DIR / 'brain' / 'tasks.json'
LOG_FILE     = OPENCLAW_DIR / 'brain' / 'heartbeat.log'
NUDGE_FILE   = OPENCLAW_DIR / 'brain' / '.nudge-trigger'  # OpenClaw watches this

def log(msg):
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M')
    with open(LOG_FILE, 'a') as f:
        f.write(f'[{timestamp}] {msg}\n')

def load_tasks():
    if not TASKS_FILE.exists():
        return []
    with open(TASKS_FILE) as f:
        return json.load(f)

def check_tasks():
    tasks = load_tasks()
    now = datetime.now()
    nudges = []

    for task in tasks:
        if task.get('status') == 'pending':
            created = datetime.fromisoformat(task.get('created_at', now.isoformat()))
            age_hours = (now - created).total_seconds() / 3600

            # Nudge if task has been pending over 24h
            if age_hours > 24:
                nudges.append(f"Task pending {age_hours:.0f}h: {task.get('title', 'unknown')}")

    return nudges

def run():
    log('Heartbeat check started')
    nudges = check_tasks()

    if nudges:
        log(f'Found {len(nudges)} stale tasks — triggering nudge')
        nudge_data = {
            'time': datetime.now().isoformat(),
            'message': 'Hey! You have tasks that have been waiting a while:\n' +
                       '\n'.join(f'• {n}' for n in nudges)
        }
        with open(NUDGE_FILE, 'w') as f:
            json.dump(nudge_data, f)
    else:
        log('All tasks healthy')

if __name__ == '__main__':
    run()
PYTHON
chmod +x /home/claw/.openclaw/brain/heartbeat.py
echo 'heartbeat written'"

echo "✅  heartbeat.py written"

# ══════════════════════════════════════════════════════════
#  STEP 5 — Schedule the cron inside the container
#  Adds the 2AM job to the container's crontab
# ══════════════════════════════════════════════════════════
echo ""
echo "⏰  Scheduling nightly cron at 2AM..."

docker exec "$CONTAINER" sh -c "
  # Install cron if not present
  apk add --no-cache dcron 2>/dev/null || true

  # Add nightly consolidation at 2AM
  echo '0 2 * * * /home/claw/.openclaw/brain/cron-nightly.sh' | crontab -

  # Add heartbeat check every hour
  echo '0 * * * * python3 /home/claw/.openclaw/brain/heartbeat.py' >> /tmp/crontab.tmp
  crontab /tmp/crontab.tmp 2>/dev/null || true

  # Start cron daemon
  crond 2>/dev/null || true

  echo 'cron scheduled'
" 2>/dev/null || echo "⚠️  Cron scheduling skipped (container may need restart)"

# ══════════════════════════════════════════════════════════
#  STEP 6 — Write tacit knowledge starter file
#  Pre-seeds the tacit memory with good defaults.
#  The agent will add to this over time.
# ══════════════════════════════════════════════════════════
echo ""
echo "🧬  Seeding tacit knowledge base..."

docker run --rm \
  -v "${NAME_LOWER}-data:/home/claw/.openclaw" \
  alpine sh -c "cat > /home/claw/.openclaw/memory/tacit/preferences.md << 'MD'
# Tacit Knowledge — $NAME
# This file is auto-updated by the nightly consolidation.
# The agent learns your preferences and adds them here over time.

## Communication Style
- Be concise and direct
- Use bullet points for lists
- Flag urgent items clearly

## Work Preferences
- (agent will fill this in as it learns)

## Rules & Constraints
- Always ask before sending emails on my behalf
- Never delete files without confirmation
- Check calendar before scheduling anything

## Lessons Learned
- (agent will add lessons from past conversations here)
MD
echo 'tacit seeded'"

echo "✅  Tacit knowledge base seeded"

# ══════════════════════════════════════════════════════════
#  Done!
# ══════════════════════════════════════════════════════════
echo ""
echo "═══════════════════════════════════════════════════════════"
echo "🧠  Premium brain fully built for: $NAME"
echo ""
echo "   memory/daily/    ← logs every chat"
echo "   memory/graph/    ← knowledge graph (fills up over time)"
echo "   memory/tacit/    ← preferences.md seeded, grows nightly"
echo "   brain/config.yaml         ← reflection ON"
echo "   brain/cron-nightly.sh     ← runs at 2AM"
echo "   brain/heartbeat.py        ← runs hourly"
echo ""
echo "   The agent will get smarter every night."
echo "   Check logs: docker logs $CONTAINER --tail 50"
echo "═══════════════════════════════════════════════════════════"
